version: '3.8'

services:
  whatsapp-ai-bot:
    build: .
    container_name: whatsapp-ai-bot
    restart: unless-stopped
    
    # Environment variables
    environment:
      # AI Models Configuration
      - USE_STREAMING=true
      - AI_MODEL=microsoft/DialoGPT-small
      - MAX_RESPONSE_LENGTH=500
      - TEMPERATURE=0.8
      - LOW_MEMORY_MODE=false
      
      # Search Configuration - SearXNG Access
      - SEARCH_ENABLED=true
      - SEARXNG_URL=http://searxng:8080
      - MAX_SEARCH_RESULTS=10
      - AUTO_SEARCH_ON_QUESTIONS=true
      
      # Translation and Timezone
      - AUTO_TRANSLATE=true
      - TARGET_LANGUAGE=en
      - TIMEZONE=Africa/Lagos
      - LOCALE=en_NG
      
      # WhatsApp Configuration
      - BOT_NAME=AI Assistant 🤖
      - BOT_PREFIX=!
      
      # Voice Configuration
      - VOICE_ENABLED=true
      - TTS_LANGUAGE=en
      - VOICE_SPEED=1.0
      
      # Feature Toggles
      - MEME_GENERATION=true
      - AUTO_REPLY_ENABLED=false
      - PERSONALITY_MODE=humorous
      
      # Performance Settings
      - TRANSFORMERS_CACHE=/app/model_cache
      - HF_HOME=/app/model_cache
      - TOKENIZERS_PARALLELISM=false
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
    
    # Mount WhatsApp credentials and data
    volumes:
      - ./wa-auth:/app/wa-auth
      - ./data:/app/data
      - whatsapp_models:/app/model_cache
      - whatsapp_logs:/app/logs
    
    # Resource limits for optimal AI model performance
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Networking
    ports:
      - "8080:8080"  # Health check port
    
    # Dependencies
    depends_on:
      - redis
      - searxng
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # Redis for SearXNG caching
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  # SearXNG search engine
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "8081:8080"  # External access port
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8081/
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    depends_on:
      - redis
    
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

volumes:
  whatsapp_models:
    driver: local
  whatsapp_logs:
    driver: local
  valkey-data:
    driver: local

networks:
  default:
    name: whatsapp-ai-network
  searxng:
    name: searxng