[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
    "trafilatura>=2.0.0",
    "yt-dlp>=2025.8.11",
]
